### ISSUE TITLE
AspNet 4.5.1 Assembly Load Failure

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#11]
Steps to reproduce:
- Install the Microsoft C++ Redistributable 2015 Preview from this repo's dependencies links
- Install NETMapnik via NuGet into an ASP.NET class assembly
- Build and execute in Debug

Error, cannot load assembly, incorrect format:

[BadImageFormatException: Could not load file or assembly 'NETMapnik' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +34
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +152
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +77
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +16
   System.Reflection.Assembly.Load(String assemblyString) +28
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38

[ConfigurationErrorsException: Could not load file or assembly 'NETMapnik' or one of its dependencies. An attempt was made to load a program with an incorrect format.]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +736
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +217
   System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +130
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +170
   System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +91
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +284
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +153
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +521

**Comment by jbrwn** [comment]
What platform are you targeting and what nuget package did you install?   This looks like a typical architecture mismatch error.  There are x86 and x64 versions of the nuget package and you must set the platform target of your assembly accordingly.

**Comment by jskulavik** [comment]
x64 package was installed and the assembly is set to target x64.

**Comment by jskulavik** [comment]
Assembly load trace, for a little more info:

=== Pre-bind state information ===
LOG: DisplayName = NETMapnik
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: NETMapnik | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.

**Comment by jbrwn** [comment]
I think there is an architecture mismatch somewhere in your workflow.   If your assembly is getting loaded by IIS/IIS express/KLR.exe can you make sure that the loading process is also running as a 64 bit process?  I know in the past there were issues with visual studio always starting up the 32 bit version of iis express by default.

**Comment by jskulavik** [comment]
Yeah, everything is set to x64.  The target version for my klr/kre project is KRE-CLR-amd64.1.0.0-beta1
 
Date: Tue, 20 Jan 2015 21:45:07 -0800

**Comment by jbrwn** [comment]
Ok - so the vNext stuff is pretty new to me but my understanding is that .NET 4.5 assembly references are not supported under the aspnet50 and aspnetcore50 target frameworks (KRE-CLR/KRE-CoreCLR).  That being said, I was able to add a net45 target to a vNext project.json file and get the project to build me a .NET 4.5 assembly (see below).  [This arcticle](http://weblog.west-wind.com/posts/2014/Dec/02/Creating-multitarget-NuGet-Packages-with-vNext) helped me get started if you are interested in pursuing this further.

```
{
    "version": "1.0.0-*",
    "dependencies": { },
    "commands": {
        "run": "run"
    },
    "frameworks": {
        "aspnet50": { },
        "aspnetcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-22231"
            }
        },
        "net45": {
            "dependencies": {
                "mapnik.x64": "1.0.0.0"
            }
        }
    }
}
```

I'm closing this issue out as this is not really a NETMapnik issue but more of a "How can i get .NET 4.5 assemblies to play nice with ASP.NET 5.0" type question.

**Comment by jskulavik** [comment]
Were you able to load NETMapnik at runtime and call it then?  Thanks
________________________________

**Comment by jbrwn** [comment]
No not if you are using the k runtime. To my knowledge the k runtime cannot load .net 4.5 assemblies.   K runtime can only load assemblies that target the aspnet50 and the aspnetcore50 frameworks.
