### ISSUE TITLE
AspNet 5 klr Assembly Load Failure

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#12]
Similar to issue #11, the new klr fails to load the NETMapnik assembly as well.

Steps to reproduce:
- In VS2015, install NETMapnik via Nuget
- Remove Core CLR compilation
- Instantiate any NETMapnik class in an AspNet5 assembly
- Run in Debug

Error: Failed to load assembly.

klr.exe Information: 0 : [LoaderContainer]: Load name=NETMapnik
'mapFactory.MapCSVGeoJson("boo")' threw an exception of type 'System.IO.FileNotFoundException'
    base: {"Could not load file or assembly 'NETMapnik, Version=0.0.5455.4976, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The specified module could not be found.":"NETMapnik, Version=0.0.5455.4976, Culture=neutral, PublicKeyToken=null"}
    FileName: "NETMapnik, Version=0.0.5455.4976, Culture=neutral, PublicKeyToken=null"
    FusionLog: ""
    Message: "Could not load file or assembly 'NETMapnik, Version=0.0.5455.4976, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The specified module could not be found."

**Comment by jbrwn** [comment]
see #11
