### ISSUE TITLE
Registering DataSources in the DatsourceCache

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#13]
Thanks again for all of the help @jbrwn.

I'm successfully loading NETMapnik into x64 .NET 4.5.1 now, but running into the exception: 

<b>Could not create datasource for type: 'csv' (no datasource plugin directories have been successfully registered)<b>

With both ".\mapnik\input" and "C:\mapnik-v2.2.0\lib\mapnik\input" supplied to DatasourceCache.RegisterDatasources then subsequently trying to instantiate a csv plugin.    

```
            JObject geojson = JObject.Parse(mapData);
            DatasourceCache.RegisterDatasources(@".\mapnik\input");
            Dictionary<string, object> options = new Dictionary<string, object>()
            {
                { "type","csv"},
                { "inline", "geojson\n'" + geojson["geometry"].ToString(Formatting.None) + "'" }
            };

            Datasource ds = new Datasource(options);
```

**Comment by jbrwn** [comment]
Looks like that should work if you installed via the nuget packages.  

>"C:\mapnik-v2.2.0\lib\mapnik\input"

That is definitely not going to work.   NETMapnik targets mapnik-sdk v3.0.  Loading plugins from a previous version will not work.   

There is not really a ton for me to go off here.  I'd like to help but there is not much i can do unless you post a full working test case.  For example, Here is a quick test case i set up too check your code:

* create a new vs2015 console application targeting .NET 4.5.1
* set platform target to x64
* add mapnik.x64.1.0.0 nuget package
* add Newtonsoft.Json.6.0.8 nuget package
* run this code:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NETMapnik;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication5
{
    class Program
    {
        static void Main(string[] args)
        {
            string input = @"{
                type: ""Feature"",
                properties: {},
                geometry: {
                    type: ""Polygon"",
                    coordinates: [[[1,1],[1,2],[2,2],[2,1],[1,1]]]
                }
            }";
            JObject geojson = JObject.Parse(input);
            DatasourceCache.RegisterDatasources(@".\mapnik\input");
            Dictionary<string, object> options = new Dictionary<string, object>()
            {
                { "type","csv"},
                { "inline", "geojson\n'" + geojson["geometry"].ToString(Formatting.None) + "'" }
            };

            Datasource ds = new Datasource(options);
            Console.ReadLine();
        }
    }
}
```

This compiles and executes without error

**Comment by lsy8qh** [comment]
![image](https://user-images.githubusercontent.com/17716886/60311888-b6546980-998b-11e9-99a3-89e50212c840.png)
![image](https://user-images.githubusercontent.com/17716886/60311907-ce2bed80-998b-11e9-89d9-58edce327f0c.png)
not found DatasourceCache！！
why？
