### ISSUE TITLE
GDAL_DATA

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#14]
I'm fairly certain this isn't a NETMapnik issue, but I keep getting:
```
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing the EPSG csv files.
```
If I point that env variable to ~\share\gdal I still get that error when trying to create a VectorTile. 

Have you seen this before?

Thanks!

**Comment by jbrwn** [comment]
Where is your GDAL_DATA directory located in relation to your NETMapnik assembly?  Your file system should look this:

```
.\bin\NETMapnik.dll
.\bin\share\gdal
```

 [NETMapnik sets the GDAL_DATA environmental variable for the running process to share\gdal](https://github.com/jbrwn/NET-Mapnik/blob/95e3f123ad7f3ceb95ae3baf20b11cfaf6c71244/NETMapnik/mapnik.cpp#L17).   So even if you set GDAL_DATA system wide it is reset when NETMapnik gets loaded.

**Comment by jskulavik** [comment]
Argh!  My bad, I forgot to include the share directory after switching to the latest build from NuGet.  I need to follow directions better!
