### ISSUE TITLE
Enabling ToGeoJSON

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#15]
Is there any reason this is commented out in NETMapnik?

```
//System::String^ ToGeoJSON(System::String^ layer);
```

Are there plans to add that back in soon?

Thanks!

**Comment by jbrwn** [comment]
It was never enabled to begin with. Implementation requires a bump to the mapnik-sdk version.  I will implement it soon and it will definitely be included in the next release.

**Comment by jskulavik** [comment]
Ahh, I see.  Thanks @jbrwn.  I'm very much in need of that functionality, so maybe I could entice you with a CO craft brew six pack? ;-)

**Comment by jbrwn** [comment]
ok - implemented @f770be43ef90f1cf0a07ca77d4ee77cf6479294f.   No need for a beer bribe.  This was already at the top of my list.  

If you are building from source you will need to update [mapnik-sdk and mapnik-vector-tile versions](  https://github.com/jbrwn/NET-Mapnik/commit/68fd0f0d656943ebb15671a606e06ceab3a8ffb3#diff-f5a1296951d2a8c757f7382b0a19b317).

**Comment by jskulavik** [comment]
Fantastic!!  Thank you very much.  I still owe you those beers though...
