### ISSUE TITLE
Missing reference on clean machine

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#16]
When downloading the mapnik.x64 package from Nuget into a solution, setting the Runtime Architecture to x64, then invoking a NET-Mapnik method, assembly load failures occur:

"Could not load file or assembly 'NETMapnik.dll' or one of its dependencies. The specified module could not be found.","ExceptionType":"System.IO.FileNotFoundException"

**Comment by jbrwn** [comment]
Do you have the x64 2015 visual c++ runtime installed?

https://github.com/jbrwn/vcredist/raw/master/2015Preview/vcredist_x64.exe

**Comment by jskulavik** [comment]
Yep.  I'm totally baffled since we've gone through this before.  I have to be forgetting something...

**Comment by jskulavik** [comment]
I have:
- .NET 4.5
- x64 target platform
- 2015 C++ Runtime

All set accordingly.

**Comment by jbrwn** [comment]
Yeah, that looks right.  I'll run through a clean install on my end to verify.  Might be a day or two until i can circle back on this.

**Comment by jskulavik** [comment]
OK, sounds good.  Thanks, and sorry for the hassles.

**Comment by jbrwn** [comment]
I could not reproduce the issue on a fresh install of windows server 2008 r2 and VS 2015 CTP 6.  Here is what i did to test:

* Create new c# 4.5 console application project
* Add Mapnik.x64 nuget package
* Set platform target to x64 on the build tab of the project properties

You might want to try using [Process Explorer]( https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) to see exactly what dependency is not getting loaded.

**Comment by jskulavik** [comment]
Very strange...I did followed the same steps, but on Windows Server 2012 R2 instead and still get the exact same error.  Process Explorer shows no additional information.  

Do you think it could be a Windows Server 2012 issue?

**Comment by jbrwn** [comment]
I do not think it is Windows Server 2012 issue.  The appveyor build for this project runs on windows server 2012 R2 and all tests load the assembly and native DLLs without a problem.   

>Process Explorer shows no additional information.

This confused me at first but now i realize I pointed you at the wrong tool.  [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) is the tool i meant to recommend.   If an assembly or one of its dependancies is not found it should show up in process monitor if you are monitoring file activity. 

This should give you a better idea of what exactly is not getting loaded at runtime.  You mind running this tool and reporting back what you find?

**Comment by BergWerkGIS** [comment]
Just tried with a fresh install of Windows Server 2012 R2 and just VS 2015 Preview on it.
I could register the shape input plugin and open a shapefile without problems.

@jskulavik can you share a SLN that fails for you?

**Comment by jskulavik** [comment]
Thanks @BergWerkGIS, here's the solution:  https://github.com/jskulavik/net-mapnik-debug/tree/master/mapconsole

**Comment by jskulavik** [comment]
This is VERY odd @jbrwn, but even process monitor shows that everything (refs) are being loaded.  No errors.  So strange...

**Comment by jskulavik** [comment]
Here's the Process Monitor output:
![success](https://cloud.githubusercontent.com/assets/2044176/7109946/4a845602-e198-11e4-966c-919f1b285c8b.png)

**Comment by BergWerkGIS** [comment]
I think, this might still have something to do with the C++ runtime.

I haven't installed any additional runtimes: just VS2015 Preview and  VS2015 CTP6, each on its own Windows Server 2012R2.

On the machine with VS2015 Preview this code works.
On the machine with VS2015 CTP6 I get the error of the original post.

```csharp
Mapnik.RegisterDatasource(@"YOUR\PATH\TO\mapnik\input\ogr.input");
VectorTile vt = new VectorTile(1, 0, 0);
vt.AddGeoJSON(@"
{
""type"": ""FeatureCollection"",
  ""features"": [
    {
      ""type"": ""Feature"",
      ""properties"": {},
      ""geometry"": {
            ""type"": ""Point"",
            ""coordinates"": [
              16.3037109375,
              49.92293545449574
            ]
        }
    }
  ]
}
", "layer0");
```

**Comment by jskulavik** [comment]
Interesting.  I wonder if this is having an effect on the runtime:  https://www.visualstudio.com/en-us/news/vs2015-vs.aspx#vcplusctp6

**Comment by BergWerkGIS** [comment]
@jskulavik What is your setup?
Which version of VS are you using?

**Comment by jskulavik** [comment]
Microsoft Visual Studio Ultimate 2015 CTP
Version 14.0.22609.0 D14REL
Microsoft .NET Framework
Version 4.6.00030

**Comment by BergWerkGIS** [comment]
Ok, so VS 2015 CTP6 it is.

Could you post a screenshot of your installed C++ runtimes.

Like this one from a machine with VS2014CTP4:
![image](https://cloud.githubusercontent.com/assets/4549888/7118667/18959df4-e201-11e4-9383-701d99456059.png)

**Comment by jskulavik** [comment]
![vcpprntms](https://cloud.githubusercontent.com/assets/2044176/7118860/0fe9e42c-e1bf-11e4-884e-075324a86a21.PNG)

**Comment by jskulavik** [comment]
Certainly some differences here...

**Comment by BergWerkGIS** [comment]
So, the redist for VS2015 Preview, the version NET-mapnik is built with, is not listed in your screenshot.
https://github.com/mapbox/windows-builds/issues/30

Have you installed CTP6 after the redist?
If so, could you try to reinstall the redist from the link [above](https://github.com/jbrwn/NET-Mapnik/issues/16#issuecomment-91680441)?

Maybe CTP6 blocks installing a runtime from an earlier CTP.

**Comment by jskulavik** [comment]
I installed the CTP6 prior to installing the redist from the NETMapnik prerequisites.  I now have:
![prevcpprt](https://cloud.githubusercontent.com/assets/2044176/7119914/aa3abcfc-e1c6-11e4-8425-160fde4bb094.PNG)

...yet still receive the same error.  Even if I remove the CTP redist (> 14.0.22310), I still get the same error.  Very odd.

**Comment by jskulavik** [comment]
@jbrwn noted that he got it running with VS2015 CTP6 though...yet another clue.

**Comment by BergWerkGIS** [comment]
Out if ideas at the moment.
Only thing I can say, I had a very bad experience with CTP6.
It rendered my main dev machine unusable that I had to reinstall the OS.

**Comment by jskulavik** [comment]
@BergWerkGIS Ouch!  We'll that's definitely a red flag.  Thanks for the ideas...

**Comment by jbrwn** [comment]
Wow great work @BergWerkGIS  and @jskulavik.   

>@jbrwn noted that he got it running with VS2015 CTP6 

I just doubled checked my install and realized that i installed VS 2015 Preview and **NOT** CTP 6. I had assumed that the [installer for VS 2015 Preview](https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs.aspx) installs the latest CTP but this is not the case.

Here is a summary of where i think we stand on this issue:

* The mapnik.x64 nuget package installs and executes successfully at run time on a machine with Visual Studio 2015 Preview.  Visual Studio 2015 Preview includes the Visual c++ 2015 preview redistributable which is a dependency of NET-Mapnik.  

* The mapnik.x64 nuget package throws a runtime error on a machine with Visual Studio 2015 CTP 6.   This behavior appears to persist even after installing the Visual c++ 2015 preview redistributable.

Please let me know if i am leaving anything out. Based on the information in this thread i think it's best to avoid CTP 6 right now.

**Comment by jskulavik** [comment]
I believe that you have summarized it perfectly @jbrwn.  Thanks.  I'll confirm this theory soon by targeting VS2015 Preview on a fresh box and report what I find.

**Comment by BergWerkGIS** [comment]
> assumed that the installer for VS 2015 Preview installs the latest CTP but this is not the case

@jbrwn FYI: The squence of Microsoft was:

20**14** CTP 2/3/4 --> 20**15** Preview --> 2015 CTP5 --> 2015 CTP6

**Comment by jskulavik** [comment]
OK, I can confirm that all is well with the following configuration on a clean box:
- Visual Studio 2013
- VC++ 2015 Runtime Preview specified [here](https://github.com/jbrwn/vcredist/raw/master/2015Preview/vcredist_x64.exe)
- [Our beloved package](http://www.nuget.org/packages/mapnik.x64/)

Thanks for helping me track this down @jbrwn & @BergWerkGIS, I really appreciate it.

**Comment by jskulavik** [comment]
Closing issue for something more descriptive.
