### ISSUE TITLE
Visual C++ Runtime Assembly Loading Failures

### ISSUE THREAD

**Issue by jskulavik** [jbrwn/NET-Mapnik#17]
In continuation of the VC++ issue pointed out with [issue 16](https://github.com/jbrwn/NET-Mapnik/issues/16), the VS2015 RC released on 4/29/2015 the issue persists.  Given that this is RC, there are probably minimal changes to the VC++ 2015 runtime in the pipeline, it's probably worth sorting this out at this point.  @jbrwn, what do you think?

**Comment by jbrwn** [comment]
> it's probably worth sorting this out at this point. 

Agreed.  Recompiling net-mapnik using a newer c++ runtime is largely dependent on the mapnik-sdk being available in the same c++ runtime flavor.   

I will check with @BergWerkGIS to see what is available.  VS2015 CTP6 is mentioned at [mapbox/windows-builds/](https://github.com/mapbox/windows-builds) so it seems like something might be available.

**Comment by jbrwn** [comment]
fyi... opened an issue at mapbox/windows-builds about mapnik-sdk availability:

mapbox/windows-builds#38

**Comment by jskulavik** [comment]
Awesome.  I commented that it would be better to target the RC runtime (latest) in the hopes that it wouldn't be another breaking change when the RTM is out

**Comment by jskulavik** [comment]
@jbrwn, now that we have an updated Mapnik SDK, can we recompile net-mapnik and give it a go?

**Comment by jbrwn** [comment]
Absolutely.  There is likely to be some work on the net-mapnik side to account for any changes in the mapnik api.  I'd gladly accept a pull request if you beat me to it.

**Comment by jskulavik** [comment]
I'll see what I can do, but my C++ skills are extremely rusty at best

**Comment by jbrwn** [comment]
Status update - i've got net-mapnik building against the updated mapnik sdk.  There are a handful of tests that are failing that i need to track down.  I should have a build available soon.   Here is the branch i'm using to track this work:

https://github.com/jbrwn/NET-Mapnik/tree/vs2015-rc

**Comment by BergWerkGIS** [comment]
\o/

**Comment by jbrwn** [comment]
Status update part 2 - All tests are passing now.  However, I'm running into issues building on appveyor and publishing a nuget packages.  I'm tracking these issues here:

http://help.appveyor.com/discussions/problems/2124-command-fails-with-error-code-255-on-visual-studio-2015-rc-image

and  

https://github.com/mapbox/windows-builds/issues/39#issuecomment-101712853

**Comment by jbrwn** [comment]
Ok - pre-release nuget packages are now available with net-mapnik built on the VS 2015 RC c++ runtime.  The version number is bumped to 2.1.0.   You can grab them on the appveyor nuget: 
https://ci.appveyor.com/nuget/net-mapnik-nb62jh3bpbuv

Or download them directly:
https://ci.appveyor.com/api/buildjobs/3vwkhojug7q0hg07/artifacts/mapnik.2.1.0-pre00090.nupkg
https://ci.appveyor.com/api/buildjobs/wvov9m7hoay785f3/artifacts/mapnik.x64.2.1.0-pre00090.nupkg

**Comment by jskulavik** [comment]
Woot!  So much for beating you to it @jbrwn... Well done, thanks!

**Comment by jbrwn** [comment]
No worries. Please let me know if you run into any issues. I'll keep this issue open until I produce a full release built on VS 2015 RC.

**Comment by jbrwn** [comment]
@jskulavik - any issues with the pre-release nuget package?  if not, i will move forward with pushing a release package to nuget.org.

**Comment by jskulavik** [comment]
@jbrwn I will make some time this evening to confirm.  Sorry, been buried lately, but I'll have an answer for you tonight.

**Comment by jbrwn** [comment]
No worries.  I'm in the same boat.  I appreciate the help with testing.

**Comment by BergWerkGIS** [comment]
Just made a quick mini test and it worked. :+1:

**Comment by jbrwn** [comment]
Right on @BergWerkGIS.  Thanks for testing.

**Comment by jskulavik** [comment]
OK, we're in the money!  I've got a very happy console app running.  I'm going to take this puppy and run with it, pushing the envelope with web-enabling it and perhaps some F# wrapping.  Thanks again @jbrwn & @BergWerkGIS , I can't express my appreciation enough.
