### ISSUE TITLE
Trying to build but failed "mutex is not supported"

### ISSUE THREAD

**Issue by Charmatzis** [jbrwn/NET-Mapnik#23]
Hi again,

I am trying to build but it fails.....
The error is 	'#error:  <mutex> is not supported when compiling with /clr or /clr:pure.	NETMapnik	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mutex' 
I have tried to copy/paste the files mutex.patch and thread.patch in the folder C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ but no luck....

Plz help me.

Christos

**Comment by jbrwn** [comment]
You need to apply the patches listed in the build dependancies.

https://github.com/jbrwn/NET-Mapnik/blob/b8aea9245ca0b629e97adcde31c38bbbd53182a2/lib/readme.md

**Comment by Charmatzis** [comment]
Yes, I have done these steps I have copied mapnik-sdk to the folder /lib/x64/mapnik-sdk and I have copied 
mapnik-vector-tile project to the folder /lib/
But I believe the patches I can not do it right... Just I have to copy the 2 patch archives into the folder C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ ... is that right? Or is there another procedure? 

Thx, for the reply.

**Comment by Charmatzis** [comment]
I finally did it...!!!!
The files mutex and thread were in read only mode. From properties I unchecked it. 
Then I run from Git Shell, I directed to "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\"
and then I run the command "git apply --stats mutex.patch" and "git apply --stats thread.patch"
And finished!!!!!

**Comment by jbrwn** [comment]
right on.  Let me know if you run into any other issues.

**Comment by akrnitian** [comment]
@Charmatzis  , i have same problem related to mutex  and i followed your step, but i am getting error like
error: corrupt patch at line 14, when i am running  this command "git apply --stat mutex.patch".

Please guide me .
