### ISSUE TITLE
Unable to set cache-features for layer added programatically

### ISSUE THREAD

**Issue by rouen-sk** [jbrwn/NET-Mapnik#27]
Mapnik XML style allowes to set `cache-features` attribute on the Layer element. This prevents multiple queries - one per-style assigned on layer. However, in my scenario I have to use layers dynamically - create them in runtime and add them to map object. And I see no option to set `cache-features` this way. Am I missing something? This is huge performance issue - with 2 styles per layer (common for roads, road labels etc.) there are twice as many queries to DB. 
Thanks!

**Comment by jbrwn** [comment]
You are correct. The feature cache option is not exposed in the layer class.  I'd be happy to accept a pull request if you want to add it.  If not, i will leave this ticket open and make sure the property gets added in the next release.

**Comment by rouen-sk** [comment]
I'd be happy to help, but I am not c++ programmer, so the code base seems like hebrew to me :) Any idea, when will be next release available? Can I do anything (besides pull request) to speed things up?

**Comment by jbrwn** [comment]
I don't have a timeline for a future release.  I wish i had more time to work on this project but things are pretty stacked up for me.  Right now, a pull request is the best option.  I can provide guidance if you decided to take a crack at it.

**Comment by jbrwn** [comment]
Thanks for the pull request.  I just published a new release with the CacheFeature property you added and pushed a new nuget package to nuget.org.   You should be ready to roll.
