### ISSUE TITLE
Can't render a vector tile

### ISSUE THREAD

**Issue by longlostbro** [jbrwn/NET-Mapnik#32]
How do I render a pbf vector tile to a png image file? I can't seem to find any documentation on this.

**Comment by jbrwn** [comment]
Have a look at the [VectorTile class tests](https://github.com/jbrwn/NET-Mapnik/blob/0dc73c3bf76a6483089d21da424c1ce8961085a2/NETMapnik.Test/VectorTileTests.cs).  This should give you some examples of how to use the class.  More specifically, [this](https://github.com/jbrwn/NET-Mapnik/blob/0dc73c3bf76a6483089d21da424c1ce8961085a2/NETMapnik.Test/VectorTileTests.cs#L226) test shows how to use VectorTile Render method to write to an image object.  The image object has methods to save to the filesystem in several different formats (including png).  

Let me know if you get lost.

**Comment by longlostbro** [comment]
So after a bit of research I found Net Mapnik to work for me. I created a node project with tilelive-tmstyle and walked through the process of converting a tm2 project to xml for mapnik. Then copied the xml it generated. Now it seems to work. Is there an easier way to convert tm2 to xml or preset xml stylesheets for styling vector tiles?

```
        Mapnik.RegisterDefaultFonts();

        Mapnik.RegisterSystemFonts();

        Mapnik.RegisterDefaultInputPlugins();

        Map = new Map(TileSize, TileSize);

        Map.Load(pathToStyleSheet, false, Path.GetDirectoryName(pathToStyleSheet));

        var v = new VectorTile(zoom, x, y);

        if (data != null)

            v.SetData(data);

        Map.Render(v);

        var image = new Image(TileSize, TileSize);

        v.Render(Map, image);

        var bytes = image.Encode("png32:z=1")`
```

**Comment by jbrwn** [comment]
> Is there an easier way to convert tm2 to xml or preset xml stylesheets for styling vector tiles?

If i recall, tm2 projects contain a project.xml xml stylesheet file.  You should be able to use this directly.  

As a side note, there is not a ton of tooling that supports server side vector tile => image rendering.   This workflow was pretty much abandoned by the mapnik and mapbox teams in favor of client side rendering.

**Comment by longlostbro** [comment]
You are correct. I was able to just use the project.xml, except for those
that use [ref].replace, then an error is thrown\* Issue: #35
https://github.com/jbrwn/NET-Mapnik/issues/35*
I am attempting to implement client side rendering but on a desktop
environment, which currently I can't find any .NET projects other than
this. This project works perfectly for what I want, the only thing I wish
it could do is support Mapbox GL json stylesheets, but tm2 will do. Thank
You.
