### ISSUE TITLE
License not mentioned in Readme

### ISSUE THREAD

**Issue by longlostbro** [jbrwn/NET-Mapnik#33]
I couldn't find the license mentioned anywhere in the readme. Also is this related to this library https://sourceforge.net/projects/mapniknet/? If so then I believe it is LGPL

**Comment by jbrwn** [comment]
The core mapnik library is released under an [LGPL license ](https://github.com/mapnik/mapnik/blob/master/COPYING) so you can consider that this is the license for this project as well.   

There is no connection between this project and the sourceforg link you provided.  The sourceforge hosted project was built around an earlier version of mapnik.   This project is built against mapnik 3 and exposes an API that is (roughly) equivalent to the node-mapnik nodejs bindings.
