### ISSUE TITLE
Is this project still being worked on?

### ISSUE THREAD

**Issue by donnyv** [jbrwn/NET-Mapnik#34]
I noticed the last release was almost a year ago. Is it still being worked on?

**Comment by jbrwn** [comment]
Define "worked on" - There is no active development but the project is still maintained.  I will continue to address issues, accept pull requests, provide guidance, etc...

Any future development on this project should target .net core which would required a complete rewrite.  I would support this effort but i don't have time right now to take this on.  More discussion on this can be found in issue #29.
