### ISSUE TITLE
ICU Problem with [ref].replace

### ISSUE THREAD

**Issue by longlostbro** [jbrwn/NET-Mapnik#35]
Could not initialize ICU resources for expression: "[ref].replace('Â·', '\n')
Is there a fix for this? A previous solution for the native can be found here https://groups.google.com/forum/#!msg/mapnik/8n8OKgVaQrM/pwgY4acTE8UJ
But I'm not sure if this applies to this library

Error can be reproduced by adding something like
    <ShieldSymbolizer placement="point" avoid-edges="false" size="9" line-spacing="-4" file="img/shield/[shield]-[reflen].svg" fontset-name="fontset-1" fill="#333333" ><![CDATA[[ref].replace('·', '\n')]]></ShieldSymbolizer>

**Comment by jbrwn** [comment]
Can you check whether the icu.dat file exists in your bin\share\icu directory?

**Comment by longlostbro** [comment]
it does not exist, only a file named "__.__"
Which is also the same in my NuGet Packages folder "packages\mapnik.2.1.1\native\share\icu\__.__"
and the filesize of __.__ is 0 bytes in both locations

**Comment by jbrwn** [comment]
Hmm.  That is unfortunate.  

Can you please try this workaround:
- [Download](https://github.com/jbrwn/NET-Mapnik/tree/master/lib) the mapnik windows sdk for you platform (x86/x64)
- Copy mapnik-sdk\share\icu\icudt54l.dat to bin\share\icu

**Comment by longlostbro** [comment]
the folder mapnik-win-sdk-14.0-x86-v3.0.0-rc1-1158-g73dbec3\mapnik-sdk\share\icu
is empty when I download it.
but the x64 sdk contains the .dat file, I copied it and it works.
Why did the nuget package not contain the dat file?

**Comment by jbrwn** [comment]
> Why did the nuget package not contain the dat file?

When the [package is created](https://github.com/jbrwn/NET-Mapnik/blob/master/mapnik.nuspec) the entire share directory from the mapnik sdk is supposed to get copied into the package.   If the dat file is missing from the x86 mapnik sdk then it will be missing from the x86 nuget package as well.  

I'll leave this ticket open so the issue gets fixed in the next release.  For now it sounds like you have a workaround.

**Comment by longlostbro** [comment]
Thank You

**Comment by longlostbro** [comment]
Could you possible add something to allow for a custom location for the icu.dat?
I've tried programatically changing the environmental variable ICU_DATA but it doesn't seem to make any difference.

**Comment by jbrwn** [comment]
I don't have time to tackle this right now but i would consider adding this feature if you want to submit a PR.  [Here](https://github.com/jbrwn/NET-Mapnik/blob/master/NETMapnik/mapnik.cpp#L244) is the code that sets the ICU_DATA environmental variable.  It is called when the net-mapnik assembly is loaded for the first time.

**Comment by longlostbro** [comment]
I understand. If I find the time I will make an attempt. Thank you.
