### ISSUE TITLE
Any news on supporting Mapnik 3.5.0?

### ISSUE THREAD

**Issue by donnyv** [jbrwn/NET-Mapnik#40]
Was wondering when support for Mapnik 3.5.0 was coming out? The upgrade with this version is support for Mapboxs new Vector Tile spec.

**Comment by jbrwn** [comment]
Unfortunately, there is no active development underway to support anything beyond mapnik 3.0.  The path forward for this project is to migrate to .NET Core compatibility.  I will not be updating any dependencies until that migration happens.  This is a major undertaking and one that i have not started myself.  If there is enough community support for it i will gladly provide guidance but right now i do not have the time to start it myself.
