### ISSUE TITLE
Install-Package mapnik failed

### ISSUE THREAD

**Issue by lg5** [jbrwn/NET-Mapnik#8]
PM> Install-Package mapnik
Installing 'mapnik 1.0.0'.
Successfully installed 'mapnik 1.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'mapnik 1.0.0'. You are trying to install this package into a project that targets 'Native,Version=v0.0', but the package does not contain any assembly references o
r content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  mapnik
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Windows server 2008 64bit +VS2015 Preview + vcredist_x64.exe

I have tried "Install-Package mapnik" and "Install-Package mapnik.x64" , but got error all the time

**Comment by jbrwn** [comment]
Looks like you might be trying to install to a c++/cli project? is this correct?  If so, this is not supported by the nuget packages.   Right now the packages only support installing to c#/vb.net projects (.NET framework version 4.5).

**Comment by lg5** [comment]
Thank you jbrwn. 
I download your NET-Mapnik source code, and two projects(NETMapnik and  NETMapnik) in the solution. Then "Install-Package mapnik" in this solution failed. Now I figure it out.

**Comment by jbrwn** [comment]
Right on.  Closing out the issue.
